server:
  port: 9002
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
    ds1:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 